menu:
- {name: 'Home', path: ''}
- {name: 'Projects', path: 'projects'}
- {name: 'Résumé', path: 'resume'}
- {name: 'Contact', path: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/joey-malinowski-65075a156/'}
- {icon: 'github', link: 'https://github.com/joemalin95'}
